---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: domain-0
  title: Domain 0
  description: |
    A sample Domain
  labels:
    tier: "my-label"
  tags:
    - test

spec:
  owner: group:team-a
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: application-0
  title: Application 0
  description: |
    A sample Application
  labels:
    tier: "my-label"
  tags:
    - test

spec:
  owner: group:team-a
  subdomainOf: domain-0
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fk-0
  title: FK 0
  description: |
    A sample Functional Component.
  labels:
    my: "label"
  tags:
    - test
  annotations:
    gitlab.com/project-slug: team-a/sample-app

spec:
  owner: group:team-a
  domain: application-0
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tk-0
  title: TK 0
  description: |
    A sample Technical Component.
  labels:
    my: "label"
  tags:
    - test
  annotations:
    gitlab.com/project-slug: team-a/sample-app

spec:
  type: technical-component
  owner: group:team-a
  system: fk-0
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-0
  title: Service 0
  description: |
    A sample service for testing Backstage functionality.
  labels:
    tier: "3"
  tags:
    - test
  annotations:
    gitlab.com/project-slug: team-a/sample-app

spec:
  type: service
  owner: group:team-a
  lifecycle: production
  system: sample-system
  providesApis:
    - sample-service
